AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  gateway-lambda-cors-example

  Sample SAM Template for gateway-lambda-cors-APIname

Globals:
  Function:
    Runtime: nodejs14.x
    Architectures:
      - x86_64
    Timeout: 10
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
      AllowOrigin: "'*'"

Resources:
  YourFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      CodeUri: lambdas/
      Events:
        Callback:
          Type: Api
          Properties:
            Path: /yourcallback
            Method: get
